### ISSUE TITLE
Output *.tex filename construction

### ISSUE THREAD

**Issue by calegria** [BS4BPP/BS-4-2DBPPGC-heterogeneous-bins#3]
The output *.tex filname is constructed using the pattern "SOL_" + input_data_filename + ".tex". If <input_data_filename> is a path containing directory names, there is an error and the output file cannot be constructed.

**Comment by MartaCabo** [comment]
_The output *.tex filname is constructed using the pattern "SOL_" + input_data_filename + ".tex". If <input_data_filename> is a path containing directory names, there is an error and the output file cannot be constructed._

We are aware of that, that's why, before running the code we copy in the appropriate directory the files the program needs to run. It is done in the .bash file, and when running only one or two instances for testing pursposes, is done manually. Thus, we can have names for the solution files that are easily identifiable.
